# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b7aa720bb4100785642365dc4d1d6828cb539aa1d1342f29653fea693d90cceb8b8f4232d76d76ebd5720158f55cd76ed7a69c336aa935ceddf7d3b550c901b

test:
  secret_key_base: 42e6b2f68c717735cfa3e26d01590a8edc64c5bad38c1ec9d896b4ceeb3ac4f5d32ca747da7953d93cd5c768e1ac293b963dc74934d3fc19421b7271c685498a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
